### ISSUE TITLE
keypress is detected as release and vice versa

### ISSUE THREAD

**Issue by jose1711** [leoagomes/axisfix#1]
compiled fine but pressing the button is translated into key_release event, releasing it is translated into key_press event. any idea why this happens?

**Comment by leoagomes** [comment]
well, it's been a _long_ time since I've messed around with this project so I'm not sure what the problem could be.

did you configure it to your pad? is it detecting the pad event wrong or sending the wrong keyboard event?

**Comment by jose1711** [comment]
the pad detection (wizard) seems to go fine - except that the up <--> down and left <--> right are reversed. this is easy to fix in the config file though. the expectation is that when i press left, "a" (in `wasd` mode) appears in an application window (and after a while autorepeat activates). currently the situation looks like this:
* `axisfix` is invoked
* i press left, nothing happens
* i release left and get an `a`, followed by many `aaaaaaaaa` in succession as a result of autorepeat
* i press left and `a`'s stop

this is on an up-to-date arch linux x86_64 with [speedlink dancepad](https://www.nejlepsiceny.cz/tema/speed-link-speed-link-dancefloor-dance-mat-sl-4047.html).

**Comment by leoagomes** [comment]
does calibrating the pad's "axis" using a tool such as [jstest-gtk](https://jstest-gtk.gitlab.io/) (`jstest-gtx-git` on AUR) before configuring the pad with `axisfix` change anything? if not, can you also send me the output of `jstest` (from the `joyutils` package) for whenever you press up/down/left/right?

on a side note: reading through Arch wiki I saw [this](https://wiki.archlinux.org/index.php/Gamepad#Dance_pads), which seems to be easier than my tool, does it solve your problem?

**Comment by jose1711** [comment]
thank you for the tip about calibration. indeed the generated config file looks differently before and after calibration:
```
$ sdiff -s noncalibrated calibrated 
vert_middle = 0						      |	vert_middle = 255
hor_middle = 0						      |	hor_middle = 255
```
But what's more important: it does not suffer from "stickiness" anymore once calibrated. `xpad` module did not help me at all. Closing.
